export const CLASSPREFIX = 'muze',
    IDFIELD = '__id__',
    CONFIG = 'config',
    DATAMODEL = 'dataModel',
    AXES = 'axes',
    LAYERDEFS = 'layerDef',
    WIDTH = 'width',
    HEIGHT = 'height',
    MOUNTPOINT = 'mountPoint',
    GRIDLINEPARENTGROUPCLASS = 'grid-lines',
    TRANSFORM = 'transform',
    CONSOLIDATED = 'consolidated',
    FRAGMENTED = 'fragmented',
    DEFAULTCOLOR = '#F44336',
    DEFAULTSIZE = 50,
    DEFAULTSHAPE = 'circle',
    STEP = 'step',
    GRADIENT = 'gradient',
    ORDINAL = 'ordinal',
    SCALE_FUNCTIONS = {
        size: 'getSize',
        shape: 'getShape',
        color: 'getColor'
    },
    TOP = 'top',
    LEFT = 'left',
    RIGHT = 'right',
    BOTTOM = 'bottom',
    HORIZONTAL = 'horizontal',
    VERTICAL = 'vertical',
    CENTER = 'center',
    VALUE = 'value',
    PATH = 'path',
    SHAPE = 'shape',
    RECT = 'rect',
    START = 'start',
    UPPER = 'upper',
    LOWER = 'lower',
    END = 'end',
    SIZE = 'size',
    DISCRETE = 'discrete',
    MEASURE = 'measure';

